### PR TITLE
Use index instead if 'dx' to access consumptionData

### LINKED ISSUE #51: pwrcons.json does contain only values with "0"
As I understood the code, the consumption values saved into pwrcons.json and read from there when starting.
In my case the plenticore.0.forecast.consumption.day was 0 after restart of the adapter. 
When I had a look on pwrcons.json, the file was updated, but I had a look with the editor, all values are 0.
So far I did not figure out why.

### PR DESCRIPTION
**Pull request by PastCoder**
I think this change resolved #51.

The access to consumption_data[][] was done with "d0", "d1", ... to update the values, but the structure was created only with index (no label). 
The solution without label is the format which is as well in the saved file. So that file and the data should be compatible now. 

To finally see if all aspects (e.g. rotation) work, the adapter need to run a few days. 
Nevertheless you may already have a look on the changes or test in parallel.

### CODE REVIEW

**Comment by StrathCole** [comment]
Honestly I don't see any reason why these changes should change any behaviour?

**Comment by PastCoder** [comment]
In my case the pwrcons.json did always contain only 0-values (and by this the average consumption was 0 after restart and probably day change). Due to this I tried to figure out why. Debug log on consumption data (from RAM) did always whow 0 values. 
In the json there are the tags "day" and "night". Within day and night there are 4 entries but without any tag (e.g. no "d0"). So the access with "[d0]" seems to fail but "[0]" works. 
Since I changed it, there are values in the pwrcons.json. After the first day for 1 entry; after 2 days now for 2 entries. And the average consumption value does not reset to 0 but uses the loaded data.

**Comment by PastCoder** [comment]
To verify if the problem and the change behave as I understood it from the initial and the changed code, I used the adapter with and without the fix and recorded the consumption data; see attached files.

I think it confirms the problem: Without the fix, the data is not correctly stored in the array. 
At 00:00 and when the adapter is restarted, the data is written into the file  /opt/iobroker/iobroker-data/plenticore.0/pwrcons.json. 
After four days all values are 0, because history of 0 days is kept in that file. When the adapter is then restarted, it reads all values 0 so that the consumtion value in the chart drops until new data is added in the day or night consumption. 

With the code change the values are correctly moved into the array. If the file is now saved, the data is contained. After 4 days for all 4 day and night values, there are values in the file. If the adapter is now restarted, it initialized with values read from the file (which are now real values and not 0 anymore). 

To test it: Check the data inside pwrcons.json after restart of the adapter. Restart again after some time (e.g. 1-2 hours). Is teh data changed?

avg_cons_with fix
avg_cons_without fix

**Comment by StrathCole** [comment]
I have currently no time to verify this, but as it should do no harm, I have merged it. Thanks.

**Pull request merged**
